//! Emits `build_info.rs` constants from the workspace `Cargo.toml`'s
//! `[workspace.metadata.app]` table. Every crate that needs the app
//! name / domain / display name pulls them from `core::build_info` —
//! no other source file may hardcode those strings (CI-enforced).

// Build scripts are tooling, not production code. panic/expect are
// the correct failure mode here (the build literally cannot proceed
// if the workspace manifest is malformed). The `println!` calls
// below are Cargo's `cargo::` directive interface — required.
//
// xtask: allow_macros — Cargo build-script directives go via println!.
#![allow(clippy::panic, clippy::expect_used, clippy::unwrap_used)]

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // crates/core/Cargo.toml → workspace root is two levels up.
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels up from crates/core/");
    let workspace_manifest = workspace_root.join("Cargo.toml");

    println!("cargo:rerun-if-changed={}", workspace_manifest.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&workspace_manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", workspace_manifest.display()));
    let manifest: toml::Value = toml::from_str(&raw).expect("parse workspace Cargo.toml");

    let app = manifest
        .get("workspace")
        .and_then(|w| w.get("metadata"))
        .and_then(|m| m.get("app"))
        .expect("[workspace.metadata.app] missing in Cargo.toml");

    let get = |key: &str| -> String {
        app.get(key)
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("[workspace.metadata.app].{key} missing or not a string"))
            .to_owned()
    };

    let display_name = get("display_name");
    let description = get("description");
    let cli_binary = get("cli_binary");
    let daemon_name = get("daemon_name");
    let domain = get("domain");
    let support_url = get("support_url");
    let homepage_url = get("homepage_url");

    // Derived: lowercase name used in paths/IDs.
    let app_name = display_name.to_lowercase();
    // Bundle ID base: <domain>.<app_name>
    let bundle_id_base = format!("{domain}.{app_name}");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("build_info.rs");

    let body = format!(
        r#"// Generated by build.rs from [workspace.metadata.app]. Do not edit.

/// Capitalized app name shown to users.
pub const DISPLAY_NAME: &str = "{display_name}";

/// Lowercase technical name (used in paths, IDs, log subsystems).
pub const APP_NAME: &str = "{app_name}";

/// One-line app description.
pub const DESCRIPTION: &str = "{description}";

/// CLI executable name (short verb, e.g. `aborg`).
pub const CLI_BINARY: &str = "{cli_binary}";

/// Daemon executable name.
pub const DAEMON_NAME: &str = "{daemon_name}";

/// Reverse-DNS domain prefix (no app suffix).
pub const DOMAIN: &str = "{domain}";

/// Bundle ID base for every helper / subprocess
/// (concatenate with `.<purpose>` to get the full ID).
pub const BUNDLE_ID_BASE: &str = "{bundle_id_base}";

/// Version from Cargo.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Support URL.
pub const SUPPORT_URL: &str = "{support_url}";

/// Homepage URL.
pub const HOMEPAGE_URL: &str = "{homepage_url}";
"#
    );

    fs::write(&dest, body).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
